version : '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: 'mysql'
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dbroot
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1.sql:ro
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql:ro
